/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Monkey(props) {
   
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(require('../../assets/Monkey.glb'))
  const { actions,names } = useAnimations(animations, group)

 
 
  useEffect(() => {
    
    console.log("actions", actions);
    console.log("names", names);
  

   

    
    actions['Cube.001Action'].play();
    actions['Cube.002Action'].play();
    actions['CubeAction'].play();
    actions['CylinderAction'].play();
    actions['Sphere.001Action'].play();

   
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Armature001"
          position={[-0.002, -0.049, -0.056]}
          rotation={[1.588, -0.006, 0]}
          scale={0.001}>
          <group name="Body">
            <skinnedMesh
              name="Cube004"
              geometry={nodes.Cube004.geometry}
              material={materials.pointeye}
              skeleton={nodes.Cube004.skeleton}
            />
            <skinnedMesh
              name="Cube004_1"
              geometry={nodes.Cube004_1.geometry}
              material={materials['Material.006']}
              skeleton={nodes.Cube004_1.skeleton}
            />
          </group>
          <group name="Ear">
            <skinnedMesh
              name="Cube005"
              geometry={nodes.Cube005.geometry}
              material={materials.pointeye}
              skeleton={nodes.Cube005.skeleton}
            />
            <skinnedMesh
              name="Cube005_1"
              geometry={nodes.Cube005_1.geometry}
              material={materials['Material.006']}
              skeleton={nodes.Cube005_1.skeleton}
            />
          </group>
          <group name="Eye">
            <skinnedMesh
              name="Sphere002"
              geometry={nodes.Sphere002.geometry}
              material={materials.pointeye}
              skeleton={nodes.Sphere002.skeleton}
            />
            <skinnedMesh
              name="Sphere002_1"
              geometry={nodes.Sphere002_1.geometry}
              material={materials.eye}
              skeleton={nodes.Sphere002_1.skeleton}
            />
            <skinnedMesh
              name="Sphere002_2"
              geometry={nodes.Sphere002_2.geometry}
              material={materials.darkeye}
              skeleton={nodes.Sphere002_2.skeleton}
            />
          </group>
          <skinnedMesh
            name="Hat"
            geometry={nodes.Hat.geometry}
            material={materials['Material.007']}
            skeleton={nodes.Hat.skeleton}
          />
          <skinnedMesh
            name="Shirt"
            geometry={nodes.Shirt.geometry}
            material={materials['Material.007']}
            skeleton={nodes.Shirt.skeleton}
          />
          <primitive object={nodes.mixamorigHips} />
        </group>
        <mesh
          name="Plane"
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials['Material.001']}
        />
      </group>
    </group>
  )
}

// useGLTF.preload('../../assets/Monkey.glb')
